BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Clients" (
	"Id"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL,
	PRIMARY KEY("Id")
);
CREATE TABLE IF NOT EXISTS "Products" (
	"Id"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Brand"	TEXT NOT NULL,
	"Price"	REAL NOT NULL,
	"ClientId"	TEXT NOT NULL,
	PRIMARY KEY("Id"),
	FOREIGN KEY("ClientId") REFERENCES "Clients"("Id") ON DELETE CASCADE
);
COMMIT;
